changelog:
  categories:
    - title: Added
      labels:
        - enhancement
    - title: Changed
      labels:
        - changed
    - title: Fixed
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
