//
//  PersistableEntity.swift
//  SwiduxPersistence
//
//  The protocol pair that lets the persistence plugin treat every
//  `@Persisted` domain entity and its generated SwiftData shadow uniformly.
//

import Foundation
import SwiftData

/// A domain entity that can be persisted via a generated SwiftData shadow model.
///
/// Conformance is generated by the `@Persisted` macro — you never write it by
/// hand. The associated ``Model`` is the generated `{Type}Model` `@Model` class.
public protocol PersistableEntity: Identifiable, Equatable, Sendable where ID == UUID {
    /// The generated SwiftData shadow class for this entity.
    associatedtype Model: PersistableModel where Model.Domain == Self
}

/// The generated SwiftData `@Model` shadow for a ``PersistableEntity``.
///
/// Conformance (and the `init(from:)`/`toDomain()`/`update(from:)` trio) is
/// generated by `@Persisted`; you never write it by hand.
public protocol PersistableModel: PersistentModel {
    /// The value-type domain entity this model shadows.
    associatedtype Domain: PersistableEntity

    /// Creates a fresh model from a domain value (used for inserts).
    init(from domain: Domain)

    /// Reconstructs the domain value from the persisted model.
    func toDomain() -> Domain

    /// Updates an existing model in place from a domain value (used for upserts),
    /// preserving SwiftData identity. Does not reassign `id`.
    func update(from domain: Domain)

    /// The entity's stable identity.
    var id: UUID { get }

    /// A monomorphic fetch descriptor locating the row for `id`.
    ///
    /// Generated per-model so the `#Predicate` binds `\Self.id` to the concrete
    /// stored attribute. A generic `#Predicate` over the protocol-required `id`
    /// is miscompiled under `-O` (the witness key path ≠ the stored-attribute
    /// key path), trapping in `modelContext.fetch`; building it concretely avoids that.
    static func swiduxFetchDescriptor(id: UUID) -> FetchDescriptor<Self>

    /// A monomorphic fetch descriptor locating every row whose `id` is in `ids`,
    /// for batched lookups (one round trip instead of one per ID).
    ///
    /// Generated per-model for the same `-O` reason as
    /// ``swiduxFetchDescriptor(id:)`` — the `#Predicate` must bind the concrete
    /// stored attribute. The requirement is optional (defaulted to `nil`) so
    /// hand-written conformances predating it keep compiling; callers such as
    /// `EntityDB.apply` fall back to per-ID fetches when it returns `nil`.
    static func swiduxBatchFetchDescriptor(ids: [UUID]) -> FetchDescriptor<Self>?
}

extension PersistableModel {
    /// Default for conformances without a generated batch descriptor: `nil`
    /// signals "no batched fetch available; use per-ID fetches".
    public static func swiduxBatchFetchDescriptor(ids: [UUID]) -> FetchDescriptor<Self>? {
        nil
    }
}
