//
//  PersistableEntity.swift
//  SwiduxPersistence
//
//  The protocol pair that lets the persistence plugin treat every
//  `@Persisted` domain entity and its generated SwiftData shadow uniformly.
//

import Foundation
import SwiftData

/// A domain entity that can be persisted via a generated SwiftData shadow model.
///
/// Conformance is generated by the `@Persisted` macro — you never write it by
/// hand. The associated ``Model`` is the generated `{Type}Model` `@Model` class.
public protocol PersistableEntity: Identifiable, Equatable, Sendable where ID == UUID {
    /// The generated SwiftData shadow class for this entity.
    associatedtype Model: PersistableModel where Model.Domain == Self
}

/// The generated SwiftData `@Model` shadow for a ``PersistableEntity``.
///
/// Conformance (and the `init(from:)`/`toDomain()`/`update(from:)` trio) is
/// generated by `@Persisted`; you never write it by hand.
public protocol PersistableModel: AnyObject {
    /// The value-type domain entity this model shadows.
    associatedtype Domain: PersistableEntity

    /// Creates a fresh model from a domain value (used for inserts).
    init(from domain: Domain)

    /// Reconstructs the domain value from the persisted model.
    func toDomain() -> Domain

    /// Updates an existing model in place from a domain value (used for upserts),
    /// preserving SwiftData identity. Does not reassign `id`.
    func update(from domain: Domain)

    /// The entity's stable identity.
    var id: UUID { get }
}
