//
//  PersistenceCoordinator.swift
//  SwiduxPersistence
//
//  Assembles a SwiftData-backed persistence stack from a list of registered
//  entities and exposes the reusable `Swidux.PersistencePlugin` plus a
//  first-load hydration gate. Built once in `Store.configured()`.
//

import Foundation
import Swidux
import SwiftData
import os

/// Owns the `ModelContainer` + generic ``EntityDB`` and wires the registered
/// entities into a `Swidux.PersistencePlugin`.
///
/// ```swift
/// extension Counter: PersistableEntity {}   // generated by @Persisted
///
/// let container = try ContainerFactory.makeLocalContainer(models: [CounterModel.self])
/// let persistence = PersistenceCoordinator<AppState, AppAction>(
///     entities: [.entity(\.counters)],
///     container: container
/// )
/// plugins.register(persistence.corePlugin)
/// var initial = AppState()
/// await persistence.hydrate(into: &initial)
/// ```
@MainActor
public final class PersistenceCoordinator<State, Action> {
    /// The reusable core persistence plugin — register it on the `PluginHost`.
    public let corePlugin: PersistencePlugin<State, Action>

    /// Indirection to the active database; swap it to redirect to a rebuilt
    /// container (used by `SwiduxCloudKitSync` when toggling sync).
    public let handle: DatabaseHandle

    private let entities: [PersistedEntity<State>]

    /// The failure and diagnostic handlers, threaded into every read and write.
    private let observers: PersistenceObservers

    /// Index-aligned with `entities`. Kept so the merge can ask each writer
    /// what it still holds unflushed.
    private let writers: [StateWriter<State>]

    /// The default policy for ``rehydrate(into:policy:)``.
    public let mergePolicy: MergePolicy

    /// Entities the app has declared it is editing, exempt from the merge until
    /// released.
    ///
    /// The other exemptions are inferred from what the store has seen; this is
    /// the one an app declares, and it covers the value a view is holding in
    /// local `@State` that was never dispatched. See ``EditingHolds``.
    public let editing = EditingHolds()

    /// The currently active database actor.
    public var database: EntityDB { handle.db }

    /// Builds the stack from registered entities and a prepared container.
    ///
    /// - Parameters:
    ///   - entities: The registered entity collections (``PersistedEntity/entity(_:)``).
    ///   - container: The prepared `ModelContainer`.
    ///   - debounce: How long the core plugin waits after the last change before flushing.
    ///   - retry: How a failed save is retried before the stack gives up and
    ///     reports a final ``PersistenceFailure``. Defaults to
    ///     ``RetryPolicy/default``.
    ///   - mergePolicy: How ``rehydrate(into:policy:)`` resolves storage
    ///     against live state. Defaults to ``MergePolicy/preferRemote``, so
    ///     remote edits and deletions surface mid-session. Individual entities
    ///     can narrow it via ``PersistedEntity/entity(_:policy:collapse:)``.
    ///   - onFailure: Called when a save or fetch fails. Every failure is
    ///     logged regardless; supply a handler to additionally surface it
    ///     (e.g. dispatch an action that shows a "couldn't save" banner).
    ///     A failed **save** means in-memory data is not on disk; a failed
    ///     **hydrate fetch** leaves that `EntityStore` untouched.
    ///   - onDiagnostic: Called for conditions that are **not** failures but
    ///     that an app may want to act on — duplicate rows collapsed on read, a
    ///     probable dispatch loop, the accumulated set of writes that never
    ///     reached disk. See ``PersistenceDiagnostic``. Duplicate reads and
    ///     dispatch loops are logged at their source whether or not a handler is
    ///     supplied; the unpersisted set is reported here only.
    public init(
        entities: [PersistedEntity<State>],
        container: ModelContainer,
        debounce: Duration = .milliseconds(250),
        retry: RetryPolicy = .default,
        mergePolicy: MergePolicy = .preferRemote,
        onFailure: PersistenceFailureHandler? = nil,
        onDiagnostic: PersistenceDiagnosticHandler? = nil
    ) {
        self.entities = entities
        self.mergePolicy = mergePolicy
        let handle = DatabaseHandle(EntityDB(modelContainer: container))
        self.handle = handle

        let logger = Logger(subsystem: "swidux", category: "persistence")
        let handler: PersistenceFailureHandler = { failure in
            logger.error(
                """
                [SwiduxPersistence] \(String(describing: failure.operation), privacy: .public) failed \
                for \(failure.entityType, privacy: .public): \
                \(failure.underlying.localizedDescription, privacy: .public)
                """
            )
            onFailure?(failure)
        }
        // Unlike failures, diagnostics are already logged where they are
        // detected — the emitter has the detail, and logging again here would
        // only duplicate it.
        let observers = PersistenceObservers(
            onFailure: handler, onDiagnostic: onDiagnostic ?? { _ in })
        self.observers = observers

        // Left nil when the app isn't listening, so a runaway loop doesn't also
        // pay to build a diagnostic nobody reads.
        var onLoop: (@MainActor (Int) -> Void)?
        if let emit = onDiagnostic {
            onLoop = { drains in emit(.possibleDispatchLoop(drainCount: drains)) }
        }

        let writers = entities.map { $0.makeWriter(handle, observers) }
        self.writers = writers
        self.corePlugin = PersistencePlugin(
            writers: writers,
            debounce: debounce,
            retry: retry,
            onLoopSuspected: onLoop
        )
    }

    /// Test seam: awaited once inside the read phase, after any flush and
    /// before any state is packed — the window that used to lose writes.
    var duringReadPhase: (@MainActor () async -> Void)?

    // MARK: - Reading without mutating

    /// Reads every persisted row of `E` **without touching state**.
    ///
    /// Use this for exports, migrations, diagnostics, and any "what's on disk?"
    /// question. Do *not* answer those by re-hydrating into a throwaway
    /// `AppState()`: that idiom reads as if it were a pure fetch but is
    /// actually a merge, so it breaks silently the moment re-hydration starts
    /// consulting the state it is handed.
    ///
    /// - Parameters:
    ///   - type: The domain entity type, e.g. `Note.self`.
    ///   - flushPending: Drains the debounce window first (the default), so the
    ///     read cannot return a stale row for an entity the user just edited.
    ///     Pass `false` on a hot path where staleness is acceptable. Never pass
    ///     `true` from inside a persist handler — the flush would await itself.
    /// - Returns: Every persisted row of `E`, in fetch order.
    /// - Throws: Whatever the underlying fetch throws. Failures are reported to
    ///   `onFailure` **and** rethrown: unlike hydration there is no state to
    ///   leave untouched here, so swallowing the error could only present an
    ///   unreadable database as "no data".
    ///
    /// `E` need not be a registered entity: reading a model that is in the
    /// container's schema but not mirrored into state is legitimate.
    public func fetchAll<E: PersistableEntity>(
        of type: E.Type,
        flushPending: Bool = true
    ) async throws -> [E] {
        try await collapsingRead(of: E.self, flushPending: flushPending) { db in
            try await db.fetchAllCollapsing(E.Model.self)
        }
    }

    /// Reads just the named rows of `E` **without touching state**.
    ///
    /// The by-ID counterpart to ``fetchAll(of:flushPending:)``, for a caller that
    /// already knows which identities it cares about: one batched fetch per 500
    /// IDs, and only those rows are materialized.
    ///
    /// IDs matching no row are skipped rather than reported. Absence here is not
    /// evidence of deletion — the row may never have existed — which is why
    /// ``mergeRemote(into:ids:deleted:policy:)`` takes its deletions from an
    /// explicit set rather than from a short result.
    ///
    /// - Parameters:
    ///   - ids: The identities to load. Duplicates and unknown IDs are harmless.
    ///   - type: The domain entity type, e.g. `Note.self`.
    ///   - flushPending: Drains the debounce window first (the default), so the
    ///     read cannot return a stale row for an entity the user just edited.
    /// - Returns: One row per matched `id`, in fetch order.
    /// - Throws: Whatever the underlying fetch throws, after reporting it to
    ///   `onFailure` — the same stance ``fetchAll(of:flushPending:)`` takes.
    public func fetch<E: PersistableEntity>(
        ids: Set<UUID>,
        of type: E.Type,
        flushPending: Bool = true
    ) async throws -> [E] {
        try await collapsingRead(of: E.self, flushPending: flushPending) { db in
            try await db.fetchCollapsing(ids: ids, as: E.Model.self)
        }
    }

    /// The shared body of the state-free reads: flush, read, report whatever was
    /// collapsed, and report-then-rethrow on failure.
    ///
    /// Rethrowing rather than swallowing is the deliberate half. Hydration has an
    /// `EntityStore` to leave untouched when a fetch fails; these reads have
    /// nothing, so eating the error could only present an unreadable database as
    /// "no data".
    private func collapsingRead<E: PersistableEntity>(
        of type: E.Type,
        flushPending: Bool,
        _ read: (EntityDB) async throws -> (domains: [E], duplicatesCollapsed: Int)
    ) async throws -> [E] {
        if flushPending { await corePlugin.flush() }
        do {
            let fetched = try await read(handle.db)
            if fetched.duplicatesCollapsed > 0 {
                observers.onDiagnostic(
                    .duplicateRowsCollapsed(
                        entityType: "\(E.self)", count: fetched.duplicatesCollapsed))
            }
            return fetched.domains
        } catch {
            observers.onFailure(
                PersistenceFailure(operation: .fetch, entityType: "\(E.self)", underlying: error))
            throw error
        }
    }

    /// The same rows as ``fetchAll(of:flushPending:)``, as a change-free
    /// ``EntityStore`` ready to `merge(from:)` or diff against live state.
    public func snapshot<E: PersistableEntity>(
        of type: E.Type,
        flushPending: Bool = true
    ) async throws -> EntityStore<E> {
        EntityStore(try await fetchAll(of: E.self, flushPending: flushPending))
    }

    /// First-load hydration: replaces each `EntityStore` with the on-disk rows.
    ///
    /// Takes `inout State` because it runs *before the store exists* — the
    /// canonical launch sequence hydrates a plain value and hands the result to
    /// `Store(initialState:)`. There is no observer to race with, so there is
    /// no lost-write hazard here. Use ``hydrate(into:)-(Store)`` if the store
    /// is already built.
    ///
    /// If a fetch fails, the corresponding `EntityStore` is left untouched
    /// (it does **not** become empty) and the failure is reported via `onFailure`.
    public func hydrate(into state: inout State) async {
        let applies = await hydratePhase()
        for apply in applies { apply(&state) }
    }

    /// Runs every registered entity's hydration read in registration order,
    /// touching no state, and returns the synchronous folds to apply.
    ///
    /// All fetches complete before any fold runs. That makes a multi-entity
    /// read atomic with respect to dispatch, and it is what lets the caller
    /// pack its snapshot after the last `await`.
    private func hydratePhase() async -> [PersistedEntity<State>.Apply] {
        var applies: [PersistedEntity<State>.Apply] = []
        applies.reserveCapacity(entities.count)
        for entity in entities {
            applies.append(await entity.readForHydrate(handle, observers))
        }
        await duringReadPhase?()
        return applies
    }

    /// Whether a re-hydration read the whole table or only named rows.
    ///
    /// The two differ in what they can conclude, not just in what they cost. A
    /// whole-table read may infer a deletion from a row's absence; a partial one
    /// may not — an ID that isn't in the result was not asked for. So the scope
    /// travels with the read and decides where deletions come from.
    private enum MergeScope {
        case wholeTable

        /// Read only these IDs, and treat `deleted` as the only evidence of
        /// removal. Declared deletions are read too: a row storage still holds
        /// is what refutes a stale tombstone, and only a fetch can tell us that.
        case ids(Set<UUID>, deleted: Set<UUID>)

        var declaredDeletions: Set<UUID> {
            if case .ids(_, let deleted) = self { return deleted }
            return []
        }

        /// The IDs to read, unioned once for the whole phase rather than per
        /// registered entity.
        var reading: Set<UUID> {
            if case .ids(let ids, let deleted) = self { return ids.union(deleted) }
            return []
        }
    }

    /// Runs every registered entity's merge read in registration order, touching
    /// no state, and returns the synchronous folds to apply.
    ///
    /// Each fold arrives with its entity's policy and dirty set already bound,
    /// resolved lazily inside the closure — so dirtiness is read once every
    /// fetch has completed, and a write that landed during the flush or during
    /// the fetch still counts as locally owned.
    ///
    /// A partial scope's ID set is flat rather than keyed by entity type:
    /// identities are UUIDs and don't collide across types, so an ID belonging
    /// to one entity simply matches no row in the others. The cost is one small
    /// round trip per unrelated entity, which is the trade for a caller that
    /// knows *which* rows changed but not necessarily *what* they are.
    private func mergePhase(_ scope: MergeScope = .wholeTable) async -> MergePhase {
        var folds: [MergeFold] = []
        folds.reserveCapacity(entities.count)
        var allReadsSucceeded = true
        let reading = scope.reading
        let deleted = scope.declaredDeletions
        for (entity, writer) in zip(entities, writers) {
            let read =
                switch scope {
                case .wholeTable: await entity.readForMerge(handle, observers)
                case .ids: await entity.readForPartialMerge(handle, observers, reading)
                }
            allReadsSucceeded = allReadsSucceeded && read.succeeded
            folds.append(fold(read.apply, entity, writer, deleted: deleted))
        }
        await duringReadPhase?()
        return MergePhase(folds: folds, allReadsSucceeded: allReadsSucceeded)
    }

    /// One entity's bound merge. Returns the IDs it declined to act on.
    fileprivate typealias MergeFold = @MainActor (inout State, MergePolicy?) -> Set<UUID>

    /// A merge phase's folds, plus what the phase can promise about them.
    ///
    /// Whole-table re-hydration ignores both flags — it re-reads everything next
    /// tick, so an unread entity or a deferred row costs one stale tick and
    /// nothing more. They exist for callers that consume evidence once.
    fileprivate struct MergePhase {
        let folds: [MergeFold]

        /// Whether every registered entity's read completed. A read that threw
        /// contributes a no-op fold, which is indistinguishable from "nothing
        /// changed" unless the phase says so.
        let allReadsSucceeded: Bool
    }

    /// What a completed merge could and could not promise.
    ///
    /// Both fields answer the same question from different ends — "is it safe to
    /// treat this window as fully consumed?" — and both must be clear before a
    /// watermark may advance past it.
    fileprivate struct MergeOutcome {
        let allReadsSucceeded: Bool

        /// Rows storage had something to say about that the merge declined to
        /// apply, because an editing hold was in force.
        let withheldIDs: Set<UUID>

        /// Whether the merge applied everything it read.
        var isComplete: Bool { allReadsSucceeded && withheldIDs.isEmpty }
    }

    /// Binds one entity's already-fetched merge to the dirty sets and the
    /// resolved policy, both read *inside* the returned closure.
    ///
    /// That lateness is the point: dirtiness is resolved once every fetch has
    /// completed, so a write that landed during the flush or during the fetch
    /// still counts as locally owned.
    private func fold(
        _ merge: @escaping PersistedEntity<State>.MergeApply,
        _ entity: PersistedEntity<State>,
        _ writer: StateWriter<State>,
        deleted: Set<UUID>
    ) -> MergeFold {
        // Lifted out field-by-field so the fold doesn't capture `entity` itself:
        // it outlives this call, and holding the whole registration would keep
        // all five of its closures — and whatever they captured — alive to read
        // two fields. `unpersisted` is a class, so the late read below still
        // sees the latest set.
        let unpersisted = entity.unpersisted
        let entityPolicy = entity.policy
        return { [mergePolicy, editing] state, override in
            // Four sources, because no one of them is complete: the writer
            // holds drained-but-unflushed IDs, the ledger holds IDs whose
            // save failed, the app's editing holds cover values that were
            // never dispatched at all, and the store's own `changes` hold
            // mutations not yet drained. `reconcile` folds in the last.
            let written = writer.pendingIDs.union(unpersisted.ids)
            let owned = written.union(editing.ids)
            // Only the holds the writer doesn't already cover are worth
            // reporting: attributing a pending write to the hold would
            // point a leak hunt at the wrong thing.
            let held = editing.ids.subtracting(written)
            var resolved = mergePolicy
            if let entityPolicy { resolved = resolved.restricted(by: entityPolicy) }
            if let override { resolved = resolved.restricted(by: override) }
            return merge(
                &state,
                MergeContext(
                    policy: resolved, locallyOwnedIDs: owned, deletedIDs: deleted, heldIDs: held))
        }
    }

    /// Runs every registered collapse resolver against storage, in registration
    /// order, touching no state.
    private func collapsePhase() async -> [PersistedEntity<State>.Apply] {
        var applies: [PersistedEntity<State>.Apply] = []
        applies.reserveCapacity(entities.count)
        for entity in entities {
            applies.append(await entity.collapseOnDisk(handle, observers))
        }
        await duringReadPhase?()
        return applies
    }

    /// Runs every registered collapse resolver against storage.
    ///
    /// Hydration and re-hydration already do this as part of their read; call
    /// it directly for an on-demand "repair my data" action, or from a
    /// remote-change observer that doesn't want a full merge. A no-op for
    /// entities registered without a resolver.
    ///
    /// Pending writes are flushed first, so a collapse can't run against a
    /// stale row and resurrect an edit the user just made.
    public func collapseDuplicates(into state: inout State) async {
        await corePlugin.flush()
        for apply in await collapsePhase() { apply(&state) }
    }
}

extension PersistenceCoordinator where State: SwiduxObservable {
    /// First-load hydration straight into a live store.
    ///
    /// Registered `EntityStore`s are **replaced** — that is what first-load
    /// means — so gate the UI on `hydrationPhase` until this returns. Slices
    /// that hold no registered entity are preserved, including changes made
    /// while the reads were in flight.
    public func hydrate(into store: Store<State, Action>) async {
        let applies = await hydratePhase()
        store.mutate { state in
            for apply in applies { apply(&state) }
        }
    }

    /// Re-hydration that reconciles stored rows into the live `EntityStore`s
    /// without dropping unflushed writes or in-progress edits (rule #8).
    ///
    /// Takes the store rather than `inout State` on purpose. Re-hydration is a
    /// mid-session operation with two `await`s in it (the flush, then the
    /// fetches), and any caller holding a state snapshot across those would
    /// overwrite everything dispatched in between. Here the flush and every
    /// fetch complete first; only then does one suspension-free step pack a
    /// fresh snapshot, merge, and unpack.
    ///
    /// Under the default ``MergePolicy/preferRemote``, remote edits and remote
    /// deletions surface mid-session. An ID is exempt whenever the local side
    /// still has something to say about it — a drained-but-unflushed write, an
    /// un-drained edit, a pending deletion, or a write whose save failed. Those
    /// always win, and that guarantee is not configurable.
    ///
    /// Pending writes and deletions are flushed to disk *before* the merge, so a
    /// remote-change refresh that fires during the debounce window can't read a
    /// stale disk row for an entity the user just edited or deleted and resurrect
    /// it. The flush closes most of the window; the dirty set closes what the
    /// remaining suspension points let through.
    ///
    /// > Important: One case can't be inferred — an edit still sitting in a
    /// > view's local `@State` has never reached the store, so a remote value
    /// > can land underneath it. Bindings made with `store.binding(_:sending:)`
    /// > dispatch on write and are covered already. Otherwise declare the edit
    /// > with ``editing`` (see ``EditingHolds``), which exempts one ID for as
    /// > long as it is being edited, or register a whole collection with
    /// > ``MergePolicy/preferInMemory``.
    ///
    /// If a fetch fails, the corresponding `EntityStore` is left untouched
    /// and the failure is reported via `onFailure`.
    ///
    /// - Parameters:
    ///   - store: The live store to reconcile.
    ///   - policy: Narrows the configured policy for this call only. Pass
    ///     ``MergePolicy/preferRemoteAdditive`` after a container rebuild,
    ///     where a row's absence says nothing about whether it was deleted.
    public func rehydrate(into store: Store<State, Action>, policy: MergePolicy? = nil) async {
        await corePlugin.flush()
        apply(await mergePhase(), to: store, policy: policy)
    }

    /// Applies a phase's folds and reports what the merge could not promise.
    ///
    /// The folds run inside one `mutate`, so the merge still lands in a single
    /// suspension-free step; collecting the withheld IDs on the way out costs
    /// nothing and is the only way a caller can learn that a row it read was
    /// deliberately not applied.
    @discardableResult
    fileprivate func apply(
        _ phase: MergePhase,
        to store: Store<State, Action>,
        policy: MergePolicy?
    ) -> MergeOutcome {
        var withheld: Set<UUID> = []
        store.mutate { state in
            for fold in phase.folds { withheld.formUnion(fold(&state, policy)) }
        }
        return MergeOutcome(allReadsSucceeded: phase.allReadsSucceeded, withheldIDs: withheld)
    }

    /// Re-hydration restricted to the rows a caller already knows changed.
    ///
    /// The O(k) counterpart to ``rehydrate(into:policy:)``, which re-reads every
    /// row of every registered entity on every tick. Where a sync signal carries
    /// *which* identities changed, this spends that knowledge: one batched fetch
    /// per 500 IDs instead of a full-table scan, and only the named entities are
    /// reconciled. Everything else in state is left exactly as it was.
    ///
    /// Every guarantee ``rehydrate(into:policy:)`` makes holds here. Pending
    /// writes are flushed first; an ID with unflushed local intent — a
    /// drained-but-unflushed write, an un-drained edit, a pending deletion, a
    /// write whose save failed, or an ``editing`` hold — always wins, and that is
    /// not configurable.
    ///
    /// > Important: A partial read cannot tell a deleted row from one that was
    /// > never asked about, so this **never** infers a deletion. An ID vanishes
    /// > only if you name it in `deleted`, and only if the resolved policy grants
    /// > ``MergePolicy/removesMissingEntities``. Name only what you have positive
    /// > evidence for — a history tombstone, not an empty fetch. In exchange,
    /// > there is no empty-snapshot guard to work around: this can remove the
    /// > last surviving entity, which ``rehydrate(into:policy:)`` cannot.
    ///
    /// An ID named in `deleted` that storage *still holds* is not removed. A live
    /// row is evidence the deletion was itself undone elsewhere; a tombstone can
    /// be stale.
    ///
    /// Registered `collapse:` resolvers do not run here — a resolver is handed
    /// the whole table and asked which rows survive, and a subset would have it
    /// judge a world it cannot see. Duplicate rows are still collapsed on read
    /// and still reported. Use ``collapseDuplicates(into:)-(Store)`` or a full
    /// ``rehydrate(into:policy:)`` to reclaim them.
    ///
    /// - Parameters:
    ///   - store: The live store to reconcile.
    ///   - ids: The identities to re-read. IDs matching no row, and IDs
    ///     belonging to another entity type, are harmless.
    ///   - deleted: Identities known to have been deleted elsewhere.
    ///   - policy: Narrows the configured policy for this call only.
    public func mergeRemote(
        into store: Store<State, Action>,
        ids: Set<UUID>,
        deleted: Set<UUID> = [],
        policy: MergePolicy? = nil
    ) async {
        await corePlugin.flush()
        apply(await mergePhase(.ids(ids, deleted: deleted)), to: store, policy: policy)
    }

    /// Runs every registered collapse resolver against storage, applying the
    /// result to a live store. See ``collapseDuplicates(into:)-(inout)``.
    public func collapseDuplicates(into store: Store<State, Action>) async {
        await corePlugin.flush()
        let applies = await collapsePhase()
        store.mutate { state in
            for apply in applies { apply(&state) }
        }
    }
}
