//
//  PersistenceCoordinator.swift
//  SwiduxPersistence
//
//  Assembles a SwiftData-backed persistence stack from a list of registered
//  entities and exposes the reusable `Swidux.PersistencePlugin` plus a
//  first-load hydration gate. Built once in `Store.configured()`.
//

import Foundation
import Swidux
import SwiftData
import os

/// Owns the `ModelContainer` + generic ``EntityDB`` and wires the registered
/// entities into a `Swidux.PersistencePlugin`.
///
/// ```swift
/// extension Counter: PersistableEntity {}   // generated by @Persisted
///
/// let container = try ContainerFactory.makeLocalContainer(models: [CounterModel.self])
/// let persistence = PersistenceCoordinator<AppState, AppAction>(
///     entities: [.entity(\.counters)],
///     container: container
/// )
/// plugins.register(persistence.corePlugin)
/// var initial = AppState()
/// await persistence.hydrate(into: &initial)
/// ```
@MainActor
public final class PersistenceCoordinator<State, Action> {
    /// The reusable core persistence plugin — register it on the `PluginHost`.
    public let corePlugin: PersistencePlugin<State, Action>

    /// Indirection to the active database; swap it to redirect to a rebuilt
    /// container (used by `SwiduxCloudKitSync` when toggling sync).
    public let handle: DatabaseHandle

    private let entities: [PersistedEntity<State>]
    private let onFailure: PersistenceFailureHandler

    /// Index-aligned with `entities`. Kept so the merge can ask each writer
    /// what it still holds unflushed.
    private let writers: [StateWriter<State>]

    /// The default policy for ``rehydrate(into:policy:)``.
    public let mergePolicy: MergePolicy

    /// The currently active database actor.
    public var database: EntityDB { handle.db }

    /// Builds the stack from registered entities and a prepared container.
    ///
    /// - Parameters:
    ///   - entities: The registered entity collections (``PersistedEntity/entity(_:)``).
    ///   - container: The prepared `ModelContainer`.
    ///   - debounce: How long the core plugin waits after the last change before flushing.
    ///   - mergePolicy: How ``rehydrate(into:policy:)`` resolves storage
    ///     against live state. Defaults to ``MergePolicy/preferRemote``, so
    ///     remote edits and deletions surface mid-session. Individual entities
    ///     can narrow it via ``PersistedEntity/entity(_:policy:collapse:)``.
    ///   - onFailure: Called when a save or fetch fails. Every failure is
    ///     logged regardless; supply a handler to additionally surface it
    ///     (e.g. dispatch an action that shows a "couldn't save" banner).
    ///     A failed **save** means in-memory data is not on disk; a failed
    ///     **hydrate fetch** leaves that `EntityStore` untouched.
    public init(
        entities: [PersistedEntity<State>],
        container: ModelContainer,
        debounce: Duration = .milliseconds(250),
        mergePolicy: MergePolicy = .preferRemote,
        onFailure: PersistenceFailureHandler? = nil
    ) {
        self.entities = entities
        self.mergePolicy = mergePolicy
        let handle = DatabaseHandle(EntityDB(modelContainer: container))
        self.handle = handle

        let logger = Logger(subsystem: "swidux", category: "persistence")
        let handler: PersistenceFailureHandler = { failure in
            logger.error(
                """
                [SwiduxPersistence] \(String(describing: failure.operation), privacy: .public) failed \
                for \(failure.entityType, privacy: .public): \
                \(failure.underlying.localizedDescription, privacy: .public)
                """
            )
            onFailure?(failure)
        }
        self.onFailure = handler

        let writers = entities.map { $0.makeWriter(handle, handler) }
        self.writers = writers
        self.corePlugin = PersistencePlugin(writers: writers, debounce: debounce)
    }

    /// Test seam: awaited once inside the read phase, after any flush and
    /// before any state is packed — the window that used to lose writes.
    var duringReadPhase: (@MainActor () async -> Void)?

    // MARK: - Reading without mutating

    /// Reads every persisted row of `E` **without touching state**.
    ///
    /// Use this for exports, migrations, diagnostics, and any "what's on disk?"
    /// question. Do *not* answer those by re-hydrating into a throwaway
    /// `AppState()`: that idiom reads as if it were a pure fetch but is
    /// actually a merge, so it breaks silently the moment re-hydration starts
    /// consulting the state it is handed.
    ///
    /// - Parameters:
    ///   - type: The domain entity type, e.g. `Note.self`.
    ///   - flushPending: Drains the debounce window first (the default), so the
    ///     read cannot return a stale row for an entity the user just edited.
    ///     Pass `false` on a hot path where staleness is acceptable. Never pass
    ///     `true` from inside a persist handler — the flush would await itself.
    /// - Returns: Every persisted row of `E`, in fetch order.
    /// - Throws: Whatever the underlying fetch throws. Failures are reported to
    ///   `onFailure` **and** rethrown: unlike hydration there is no state to
    ///   leave untouched here, so swallowing the error could only present an
    ///   unreadable database as "no data".
    ///
    /// `E` need not be a registered entity: reading a model that is in the
    /// container's schema but not mirrored into state is legitimate.
    public func fetchAll<E: PersistableEntity>(
        of type: E.Type,
        flushPending: Bool = true
    ) async throws -> [E] {
        if flushPending { await corePlugin.flush() }
        do {
            return try await handle.db.fetchAll(of: E.self)
        } catch {
            onFailure(PersistenceFailure(operation: .fetch, entityType: "\(E.self)", underlying: error))
            throw error
        }
    }

    /// The same rows as ``fetchAll(of:flushPending:)``, as a change-free
    /// ``EntityStore`` ready to `merge(from:)` or diff against live state.
    public func snapshot<E: PersistableEntity>(
        of type: E.Type,
        flushPending: Bool = true
    ) async throws -> EntityStore<E> {
        EntityStore(try await fetchAll(of: E.self, flushPending: flushPending))
    }

    /// First-load hydration: replaces each `EntityStore` with the on-disk rows.
    ///
    /// Takes `inout State` because it runs *before the store exists* — the
    /// canonical launch sequence hydrates a plain value and hands the result to
    /// `Store(initialState:)`. There is no observer to race with, so there is
    /// no lost-write hazard here. Use ``hydrate(into:)-(Store)`` if the store
    /// is already built.
    ///
    /// If a fetch fails, the corresponding `EntityStore` is left untouched
    /// (it does **not** become empty) and the failure is reported via `onFailure`.
    public func hydrate(into state: inout State) async {
        let applies = await hydratePhase()
        for apply in applies { apply(&state) }
    }

    /// Runs every registered entity's hydration read in registration order,
    /// touching no state, and returns the synchronous folds to apply.
    ///
    /// All fetches complete before any fold runs. That makes a multi-entity
    /// read atomic with respect to dispatch, and it is what lets the caller
    /// pack its snapshot after the last `await`.
    private func hydratePhase() async -> [PersistedEntity<State>.Apply] {
        var applies: [PersistedEntity<State>.Apply] = []
        applies.reserveCapacity(entities.count * 2)
        // Collapse first, so the read that follows sees the reclaimed store.
        for entity in entities {
            applies.append(await entity.collapseOnDisk(handle, onFailure))
        }
        for entity in entities {
            applies.append(await entity.readForHydrate(handle, onFailure))
        }
        await duringReadPhase?()
        return applies
    }

    /// The re-hydration equivalent of ``hydratePhase()``.
    ///
    /// Returns folds that still need a ``MergeContext``. Dirtiness is
    /// deliberately *not* captured here: it is read in ``applyMerge(_:to:policy:)``
    /// once every fetch has completed, so a write that landed during the flush
    /// or during the fetch still counts as locally owned.
    private func mergePhase() async -> MergeFolds<State> {
        var collapses: [PersistedEntity<State>.Apply] = []
        for entity in entities {
            collapses.append(await entity.collapseOnDisk(handle, onFailure))
        }
        var merges: [PersistedEntity<State>.MergeApply] = []
        for entity in entities {
            merges.append(await entity.readForMerge(handle, onFailure))
        }
        await duringReadPhase?()
        return MergeFolds(collapses: collapses, merges: merges)
    }

    /// Applies merge folds, resolving each entity's policy and dirty set now —
    /// after the fetches, synchronously, with no suspension point in sight.
    ///
    /// Reading dirtiness here rather than before the fetch is the whole point:
    /// a write dispatched while the fetch was in flight is in the writer's
    /// buffers by now, and would have been missed if the set had been snapshot
    /// earlier.
    private func applyMerge(
        _ folds: MergeFolds<State>,
        to state: inout State,
        policy override: MergePolicy?
    ) {
        // Collapse removals first, and they record changes, so the merge that
        // follows cannot re-absorb a collapsed-away entity.
        for collapse in folds.collapses { collapse(&state) }

        for (index, merge) in folds.merges.enumerated() {
            let entity = entities[index]
            // Three sources, because no one of them is complete: the writer
            // holds drained-but-unflushed IDs, the ledger holds IDs whose save
            // failed, and the store's own `changes` hold mutations that have
            // not been drained yet. `reconcile` folds in the third.
            let owned = writers[index].pendingIDs.union(entity.unpersisted.ids)
            var resolved = mergePolicy
            if let entityPolicy = entity.policy { resolved = resolved.restricted(by: entityPolicy) }
            if let override { resolved = resolved.restricted(by: override) }
            merge(&state, MergeContext(policy: resolved, locallyOwnedIDs: owned))
        }
    }

    /// Runs every registered collapse resolver against disk.
    ///
    /// Hydration and re-hydration already do this; call it directly for an
    /// on-demand "repair my data" action, or from a remote-change observer that
    /// doesn't want a full merge. A no-op for entities registered without a
    /// resolver.
    ///
    /// Pending writes are flushed first, so a collapse can't run against a
    /// stale row and resurrect an edit the user just made.
    public func collapseDuplicates(into state: inout State) async {
        await corePlugin.flush()
        var applies: [PersistedEntity<State>.Apply] = []
        for entity in entities {
            applies.append(await entity.collapseOnDisk(handle, onFailure))
        }
        for apply in applies { apply(&state) }
    }
}

extension PersistenceCoordinator where State: SwiduxObservable {
    /// First-load hydration straight into a live store.
    ///
    /// Registered `EntityStore`s are **replaced** — that is what first-load
    /// means — so gate the UI on `hydrationPhase` until this returns. Slices
    /// that hold no registered entity are preserved, including changes made
    /// while the reads were in flight.
    public func hydrate(into store: Store<State, Action>) async {
        let applies = await hydratePhase()
        await store.mutate {
            applies
        } merging: { applies, state in
            for apply in applies { apply(&state) }
        }
    }

    /// Re-hydration that reconciles stored rows into the live `EntityStore`s
    /// without dropping unflushed writes or in-progress edits (rule #8).
    ///
    /// Takes the store rather than `inout State` on purpose. Re-hydration is a
    /// mid-session operation with two `await`s in it (the flush, then the
    /// fetches), and any caller holding a state snapshot across those would
    /// overwrite everything dispatched in between. Here the flush and every
    /// fetch complete first; only then does one suspension-free step pack a
    /// fresh snapshot, merge, and unpack.
    ///
    /// Under the default ``MergePolicy/preferRemote``, remote edits and remote
    /// deletions surface mid-session. An ID is exempt whenever the local side
    /// still has something to say about it — a drained-but-unflushed write, an
    /// un-drained edit, a pending deletion, or a write whose save failed. Those
    /// always win, and that guarantee is not configurable.
    ///
    /// Pending writes and deletions are flushed to disk *before* the merge, so a
    /// remote-change refresh that fires during the debounce window can't read a
    /// stale disk row for an entity the user just edited or deleted and resurrect
    /// it. The flush closes most of the window; the dirty set closes what the
    /// remaining suspension points let through.
    ///
    /// > Important: One case is beyond reach — an edit that is still in a view's
    /// > local `@State` and has not been dispatched yet is invisible to the
    /// > store, so a remote value can land underneath it. Bindings made with
    /// > `store.binding(_:sending:)` dispatch on write and are therefore
    /// > covered. For a store backing a live text editor, register it with
    /// > ``MergePolicy/preferInMemory``.
    ///
    /// If a fetch fails, the corresponding `EntityStore` is left untouched
    /// and the failure is reported via `onFailure`.
    ///
    /// - Parameters:
    ///   - store: The live store to reconcile.
    ///   - policy: Narrows the configured policy for this call only. Pass
    ///     ``MergePolicy/preferRemoteAdditive`` after a container rebuild,
    ///     where a row's absence says nothing about whether it was deleted.
    public func rehydrate(into store: Store<State, Action>, policy: MergePolicy? = nil) async {
        await corePlugin.flush()
        let folds = await mergePhase()
        await store.mutate {
            folds
        } merging: { folds, state in
            self.applyMerge(folds, to: &state, policy: policy)
        }
    }

    /// Runs every registered collapse resolver against disk, applying the
    /// result to a live store. See ``collapseDuplicates(into:)-(inout)``.
    public func collapseDuplicates(into store: Store<State, Action>) async {
        await corePlugin.flush()
        var applies: [PersistedEntity<State>.Apply] = []
        for entity in entities {
            applies.append(await entity.collapseOnDisk(handle, onFailure))
        }
        await store.mutate {
            applies
        } merging: { applies, state in
            for apply in applies { apply(&state) }
        }
    }
}
