//
//  PersistableEntity.swift
//  SwiduxPersistence
//
//  The protocol pair that lets the persistence plugin treat every
//  `@Persisted` domain entity and its generated SwiftData shadow uniformly.
//

import Foundation
import SwiftData

/// A domain entity that can be persisted via a generated SwiftData shadow model.
///
/// Conformance is generated by the `@Persisted` macro — you never write it by
/// hand. The associated ``Model`` is the generated `{Type}Model` `@Model` class.
public protocol PersistableEntity: Identifiable, Equatable, Sendable where ID == UUID {
    /// The generated SwiftData shadow class for this entity.
    associatedtype Model: PersistableModel where Model.Domain == Self
}

/// The generated SwiftData `@Model` shadow for a ``PersistableEntity``.
///
/// Conformance (and the `init(from:)`/`toDomain()`/`update(from:)` trio) is
/// generated by `@Persisted`; you never write it by hand.
public protocol PersistableModel: PersistentModel {
    /// The value-type domain entity this model shadows.
    associatedtype Domain: PersistableEntity

    /// Creates a fresh model from a domain value (used for inserts).
    init(from domain: Domain)

    /// Reconstructs the domain value from the persisted model.
    func toDomain() -> Domain

    /// Updates an existing model in place from a domain value (used for upserts),
    /// preserving SwiftData identity. Does not reassign `id`.
    func update(from domain: Domain)

    /// The entity's stable identity.
    var id: UUID { get }

    /// A monomorphic fetch descriptor locating every row whose `id` is in `ids`.
    ///
    /// Generated per-model so the `#Predicate` binds `\Self.id` to the concrete
    /// stored attribute. A generic `#Predicate` over the protocol-required `id`
    /// is miscompiled under `-O` (the witness key path ≠ the stored-attribute
    /// key path), trapping in `modelContext.fetch`; building it concretely
    /// avoids that. CI runs `swift test -c release` to keep that regression
    /// class caught.
    ///
    /// It carries no `fetchLimit`: `id` has no unique constraint (CloudKit
    /// forbids one), so a lookup for a single ID may legitimately return several
    /// rows and every caller must see all of them. See ``EntityDB`` for what
    /// that implies for reads and writes.
    static func swiduxBatchFetchDescriptor(ids: [UUID]) -> FetchDescriptor<Self>

    /// A monomorphic fetch descriptor locating the rows in `persistentIDs`.
    ///
    /// Generated per-model for the reason above: `persistentModelID` is a
    /// `PersistentModel` requirement too, so a generic `#Predicate` over it is
    /// the same shape. Measured, that one translates correctly today — but it
    /// resolves the identifiers persistent history hands back, where the
    /// failure mode is merging nothing at all, silently. Requiring the
    /// descriptor makes the rule structural rather than a comment somebody has
    /// to read.
    static func swiduxBatchFetchDescriptor(
        persistentIDs: [PersistentIdentifier]
    ) -> FetchDescriptor<Self>
}
